type: single # single|window, maybe add opt
key: flcsp #added to the csv names
evaluation: evaluation #evaluation|evaluation_last|evaluation_multiple|evaluation_user_based|evaluation_user_based_multiple
data:
  name: rsc15 #added in the end of the csv names
  folder: data/rsc15/fulltrain/rsc15By64/
  prefix: rsc15
results:
  folder: results/
  
metrics:
- class: accuracy.MRR
  length: [3,5,10,15,20]
- class: accuracy.HitRate
  length: [3,5,10,15,20]
- class: coverage.Coverage
  length: [20]
- class: popularity.Popularity
  length: [20]
- class: saver.Saver
  length: [50]
- class: time_memory_usage.Time_usage_training
- class: time_memory_usage.Time_usage_testing

algorithms:
- class: FLCSP.FLCSP_cate.FLCSP_cate      
  params: {epoch: 15, lr: 0.0005, batch_size: 300, embedding_size: 50, hidden_size: 100, dropout: 0.2, l2: 0.00001}
  key: FLCSP_cate
